# Generated by Django 4.2.16 on 2024-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'date'], name='data_fetche_symbol_672169_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
